# Documentation: https://docs.travis-ci.com/user/languages/ruby/

# Language
language: ruby

# Version
rvm:
  - 2.2.0

# Vars
env:
  - DB=postgresql

# Install
before_script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace

# Cache bundler
cache: bundler

# Notifications
notifications:
  email: false
